name: Android CI/CD

on: [push, pull_request]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v5

        - name: List and Read files
          run: |
            echo "My first GitHub Action workflow"
            ls
            cat README.md
